import express from "express";
import path from "path";
import fs from "fs";
import { createServer as createViteServer } from "vite";

interface PingLog {
  status: "up" | "down";
  responseTime: number;
  statusCode: number | null;
  error?: string;
  timestamp: string;
}

interface Monitor {
  id: string;
  name: string;
  url: string;
  interval: number; // in seconds
  status: "up" | "down" | "paused" | "pending";
  lastCheck: string | null;
  avgResponseTime: number;
  uptimeRatio: number; // percentage
  history: PingLog[];
}

interface ScrollSession {
  id: string; // generated by bookmarklet/tab
  url: string;
  title: string;
  interval: number; // in seconds
  lastHeartbeat: string;
  scrollCount: number;
  userAgent: string;
  status: "active" | "inactive";
}

const PORT = 3000;
const DATA_DIR = path.join(process.cwd(), "data");
const MONITORS_FILE = path.join(DATA_DIR, "monitors.json");

// Ensure data directory exists
if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
}

// Load monitors from file or initialize
let monitors: Monitor[] = [];
if (fs.existsSync(MONITORS_FILE)) {
  try {
    const data = fs.readFileSync(MONITORS_FILE, "utf8");
    monitors = JSON.parse(data);
  } catch (err) {
    console.error("Failed to parse monitors file, initializing empty:", err);
    monitors = [];
  }
} else {
  // Add a few default demo monitors
  monitors = [
    {
      id: "demo-google",
      name: "Google Search",
      url: "https://www.google.com",
      interval: 60,
      status: "pending",
      lastCheck: null,
      avgResponseTime: 0,
      uptimeRatio: 100,
      history: []
    },
    {
      id: "demo-github",
      name: "GitHub Status",
      url: "https://github.com",
      interval: 120,
      status: "pending",
      lastCheck: null,
      avgResponseTime: 0,
      uptimeRatio: 100,
      history: []
    }
  ];
  saveMonitors();
}

function saveMonitors() {
  try {
    fs.writeFileSync(MONITORS_FILE, JSON.stringify(monitors, null, 2), "utf8");
  } catch (err) {
    console.error("Failed to save monitors:", err);
  }
}

// In-memory active scroll sessions
let scrollSessions: Record<string, ScrollSession> = {};

// Helper to clean up old scroll sessions (inactive for > 2 minutes)
function cleanScrollSessions() {
  const now = Date.now();
  Object.keys(scrollSessions).forEach((id) => {
    const lastHb = new Date(scrollSessions[id].lastHeartbeat).getTime();
    if (now - lastHb > 120 * 1000) {
      scrollSessions[id].status = "inactive";
    }
    // Delete sessions older than 1 hour to prevent leak
    if (now - lastHb > 3600 * 1000) {
      delete scrollSessions[id];
    }
  });
}

// Background ping checker
async function pingUrl(url: string): Promise<{ status: "up" | "down"; responseTime: number; statusCode: number | null; error?: string }> {
  const startTime = Date.now();
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 8000); // 8 second timeout

    const res = await fetch(url, {
      method: "GET",
      headers: {
        "User-Agent": "UptimeScrollRobot/1.0 (Keep-Alive Monitor)"
      },
      signal: controller.signal
    });
    clearTimeout(timeoutId);

    const responseTime = Date.now() - startTime;
    return {
      status: res.status >= 200 && res.status < 400 ? "up" : "down",
      responseTime,
      statusCode: res.status,
      error: res.status >= 400 ? `HTTP Error ${res.status}` : undefined
    };
  } catch (err: any) {
    const responseTime = Date.now() - startTime;
    return {
      status: "down",
      responseTime,
      statusCode: null,
      error: err.name === "AbortError" ? "Connection timeout (8s)" : err.message || "Failed to connect"
    };
  }
}

async function runPendingChecks() {
  const now = new Date();
  let changed = false;

  for (const monitor of monitors) {
    if (monitor.status === "paused") continue;

    const lastCheckTime = monitor.lastCheck ? new Date(monitor.lastCheck).getTime() : 0;
    const elapsedSeconds = (now.getTime() - lastCheckTime) / 1000;

    if (!monitor.lastCheck || elapsedSeconds >= monitor.interval) {
      const result = await pingUrl(monitor.url);
      
      const newLog: PingLog = {
        status: result.status,
        responseTime: result.responseTime,
        statusCode: result.statusCode,
        error: result.error,
        timestamp: now.toISOString()
      };

      // Limit history to 30 items
      monitor.history = [newLog, ...monitor.history].slice(0, 30);
      monitor.status = result.status;
      monitor.lastCheck = now.toISOString();

      // Recalculate average response time of successful pings
      const successfulPings = monitor.history.filter(h => h.status === "up");
      if (successfulPings.length > 0) {
        monitor.avgResponseTime = Math.round(
          successfulPings.reduce((sum, h) => sum + h.responseTime, 0) / successfulPings.length
        );
      } else if (monitor.history.length > 0) {
        monitor.avgResponseTime = Math.round(
          monitor.history.reduce((sum, h) => sum + h.responseTime, 0) / monitor.history.length
        );
      }

      // Recalculate uptime ratio
      const upCount = monitor.history.filter(h => h.status === "up").length;
      monitor.uptimeRatio = Math.round((upCount / monitor.history.length) * 100);

      changed = true;
    }
  }

  if (changed) {
    saveMonitors();
  }
}

// Start checker loop (every 5 seconds)
setInterval(runPendingChecks, 5000);
// Clean sessions every 10 seconds
setInterval(cleanScrollSessions, 10000);

async function startServer() {
  const app = express();

  // Middleware for parsing JSON
  app.use(express.json());

  // CORS middleware for the API (especially heartbeat which runs cross-origin from bookmarklet)
  app.use((req, res, next) => {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept, Authorization");
    
    // Handle OPTIONS preflight requests
    if (req.method === "OPTIONS") {
      res.sendStatus(200);
    } else {
      next();
    }
  });

  // API - Get all monitors
  app.get("/api/monitors", (req, res) => {
    res.json(monitors);
  });

  // API - Add monitor
  app.post("/api/monitors", (req, res) => {
    const { name, url, interval } = req.body;
    if (!name || !url) {
      res.status(400).json({ error: "Name and URL are required" });
      return;
    }

    let normalizedUrl = url.trim();
    if (!/^https?:\/\//i.test(normalizedUrl)) {
      normalizedUrl = `https://${normalizedUrl}`;
    }

    const newMonitor: Monitor = {
      id: Math.random().toString(36).substring(2, 11),
      name: name.trim(),
      url: normalizedUrl,
      interval: parseInt(interval, 10) || 60,
      status: "pending",
      lastCheck: null,
      avgResponseTime: 0,
      uptimeRatio: 100,
      history: []
    };

    monitors.push(newMonitor);
    saveMonitors();
    res.status(201).json(newMonitor);
  });

  // API - Delete monitor
  app.delete("/api/monitors/:id", (req, res) => {
    const { id } = req.params;
    const index = monitors.findIndex(m => m.id === id);
    if (index === -1) {
      res.status(404).json({ error: "Monitor not found" });
      return;
    }

    monitors.splice(index, 1);
    saveMonitors();
    res.json({ success: true });
  });

  // API - Pause/Resume monitor
  app.post("/api/monitors/:id/toggle", (req, res) => {
    const { id } = req.params;
    const monitor = monitors.find(m => m.id === id);
    if (!monitor) {
      res.status(404).json({ error: "Monitor not found" });
      return;
    }

    if (monitor.status === "paused") {
      monitor.status = "pending";
    } else {
      monitor.status = "paused";
    }

    saveMonitors();
    res.json(monitor);
  });

  // API - Receive Heartbeat from Bookmarklet (runs on external sites!)
  app.post("/api/scroll-sessions/heartbeat", (req, res) => {
    const { id, url, title, interval, scrollCount } = req.body;
    if (!id || !url) {
      res.status(400).json({ error: "ID and URL are required" });
      return;
    }

    const now = new Date().toISOString();
    
    scrollSessions[id] = {
      id,
      url,
      title: title || url,
      interval: parseInt(interval, 10) || 60,
      lastHeartbeat: now,
      scrollCount: parseInt(scrollCount, 10) || 0,
      userAgent: req.headers["user-agent"] || "Unknown Browser",
      status: "active"
    };

    res.json({ success: true, timestamp: now });
  });

  // API - Get active scroll sessions
  app.get("/api/scroll-sessions", (req, res) => {
    cleanScrollSessions();
    res.json(Object.values(scrollSessions));
  });

  // API - Clean/clear all inactive scroll sessions
  app.post("/api/scroll-sessions/clear", (req, res) => {
    Object.keys(scrollSessions).forEach(id => {
      if (scrollSessions[id].status === "inactive") {
        delete scrollSessions[id];
      }
    });
    res.json(Object.values(scrollSessions));
  });

  // Vite integration for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa"
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Uptime & Scroll Keeper Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer().catch((err) => {
  console.error("Failed to start server:", err);
});
